version: '2'
services:
  mongo:
    container_name: todo-db
    image: mongo
    volumes:
      - "./todo_test_db:/data/db"
    restart: always
    ports:
      - "27018:27017"
    expose:
      - 27018